version: '3.9'
services:
  # Mysql
  Mysql:
    container_name: mysql_container
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: BE-LIKE-BRO
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - mysql-volumes:/var/lib/mysql
  # Mongodb
  Mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
    - 27017:27017
    volumes:
      - mongodb-volumes:/data/db
  # Nodejs App
  app:
    build: .
    ports:
      - 51005:51005
    depends_on:
      - Mongodb
      - Mysql
# volume List
volumes:
  mysql-volumes:
  mongodb-volumes: